#!/bin/bash

###################################################################################################
#This file automatically starts a given application on startup                                    
#You can add your own app here by adding an & after the last entry and typing the desired Command 
#For Example                                                                                                                          
#htop &
#chromium-browser

####################################################################################################

# Disable any form of screen saver / screen blanking / power management
xset s off
xset s noblank
xset -dpms

# Allow quitting the X server with CTRL-ATL-Backspace
setxkbmap -option terminate:ctrl_alt_bksp

#Start Remmina in kiosk mode
remmina &

/opt/Citrix/ICAClient/selfservice --icaroot/opt/Citrix/ICAClient
# Start Chromium in kiosk mode
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
chromium-browser --disable-infobars --kiosk 'https://kd2flz.github.io/cci-kiosk' #Change this URL to desired web address



